mode: 'test'
use_perceptual_loss: false

model:
  name: 'SupResDiffGAN'
  
  # 1. LOAD YOUR BEST MODEL
  load_model: "models/checkpoints/SupResDiffGAN-epoch=204-val/LPIPS=0.148.ckpt"

# 2. MATCH THE SCRIPT'S WANDB KEYS
wandb:
  project: 'SupResDiffGAN'
  entity: 'samarthya04-kiit-deemed-to-be-university'

dataset:
  name: 'celeb'
  batch_size: 32
  resize: true
  scale: 4

evaluation:
  mode: 'all'
  
  # 3. FIX THE STEPS
  # Steps must be less than or equal to diffusion.timesteps (200)
  steps:
    - 50
    - 100
    - 200 
  posteriors:
    - 'ddpm'
    - 'ddim'
  save_results: true
  results_file: 'evaluation_results/final_evaluation.csv'

# --- Model architecture MUST match the trained model ---

autoencoder: 'VAE'
feature_extractor: true

unet:
  - 64
  - 96
  - 128
  - 256

diffusion:
  timesteps: 200
  beta_type: 'cosine'
  posterior_type: 'ddpm'
  
  # These are not used by the new script, but it's good to keep them
  # as a record of what the model was trained with.
  validation_timesteps: 100
  validation_posterior_type: 'ddim'

discriminator:
  in_channels: 6
  channels:
    - 64
    - 128
    - 256