mode: 'train-test'
use_perceptual_loss: false

model:
  name: 'SupResDiffGAN'
  lr: 0.0001
  alfa_perceptual: 0.001
  alfa_adv: 0.005
  load_model: null

trainer:
  max_epochs: 200
  max_steps: -1
  check_val_every_n_epoch: 10
  limit_val_batches: 0.05
  log_every_n_steps: 100
  precision: 16
  accelerator: 'gpu'
  devices: 1
  resume_from_checkpoint: 'models/checkpoints/SupResDiffGAN-epoch=109-val/LPIPS=0.160.ckpt'

dataset:
  name: 'celeb'
  batch_size: 32  # Reduced batch size
  resize: true
  scale: 4

evaluation:
  mode: 'all'
  steps:
    - 100
    - 200
    - 500
  posteriors:
    - 'ddpm'
    - 'ddim'
  save_results: true
  results_file: 'evaluation_results/steps_evaluation.csv'

checkpoint:
  monitor: 'val/LPIPS'
  dirpath: 'models/checkpoints/'
  save_top_k: 1
  mode: 'min'
  filename: 'SupResDiffGAN-{epoch:02d}-{val_LPIPS:.3f}'

autoencoder: 'VAE'
feature_extractor: true

unet:
  - 32
  - 32
  - 64
  - 64

diffusion:
  timesteps: 50
  beta_type: 'cosine'
  posterior_type: 'ddpm'
  validation_timesteps: 25
  validation_posterior_type: 'ddim'

discriminator:
  in_channels: 6
  channels:
    - 32
    - 32
    - 64

wandb_logger:
  project: 'SupResDiffGAN' # your wandb project
  entity: 'samarthya04-kiit-deemed-to-be-university'
