mode: 'train-test'
use_perceptual_loss: true  # Moved to root level

model:
  name: 'SupResDiffGAN'
  lr: 0.0001
  alfa_perceptual: 0.001
  alfa_adv: 0.005
  load_model: null

wandb_logger:
  project: 'SupResDiffGAN'
  entity: 'samarthya04-kiit-deemed-to-be-university'

trainer:
  max_epochs: 20  # Reduced for demo (~4-6 hours on RTX 4050)
  max_steps: -1
  check_val_every_n_epoch: 5
  limit_val_batches: 0.1
  log_every_n_steps: 50
  precision: '16-mixed'

dataset:
  name: 'celeb'
  batch_size: 2  # Safe for 6GB VRAM
  resize: true
  scale: 4

evaluation:
  mode: 'all'
  steps:
    - 100
    - 200
    - 500
  posteriors:
    - 'ddpm'
    - 'ddim'
  save_results: true
  results_file: 'evaluation_results/steps_evaluation.csv'

checkpoint:
  monitor: 'val/LPIPS'
  dirpath: 'models/checkpoints/'
  save_top_k: 1
  mode: 'min'
  filename: 'SupResDiffGAN-{epoch:02d}-{val_LPIPS:.3f}'

autoencoder: 'VAE'
feature_extractor: true

unet:
  - 32  # Reduced for memory efficiency
  - 64
  - 96
  - 128

diffusion:
  timesteps: 1000
  beta_type: 'cosine'
  posterior_type: 'ddpm'
  validation_timesteps: 500
  validation_posterior_type: 'ddim'

discriminator:
  in_channels: 6
  channels:
    - 32  # Aligned with UNet for consistency
    - 64
    - 128